export const PARTY_SPECIAL = {
    'constitution': [ // 14
        'Absorb',
        'Blind',
        'Desperation',
        'Dispel',
        'Healing',
        'Ilirech',
        'Maiereth',
        'Kyrnaicism', 
        'Kynisos', 
        'Mend',
        'Paralyze',
        'Reconstitute',
        'Renewal',
        'Shield',
        'Shirk',
        'Tether',
        'Ward'
    ], // 14 
    'strength': [ // 14
        'Arc',
        'Blind',
        'Caerenesis',
        'Desperation',
        'Devour',
        'Healing',
        'Hook',
        'Howl',
        'Leap',
        'Quor',
        'Reconstitute',
        'Rush',
        'Scream',
        'Sprint',
        'Storm',
        'Tether',
        'Ward',
        'Writhe'
    ], // 14
    'agility': [ // 14
        'Achire',
        'Desperation',
        'Envelop',
        'Healing',
        'Hook',
        'Kynisos',
        'Leap',
        'Pursuit',
        'Reconstitute',
        'Rush',
        'Shadow',
        'Shimmer',
        'Snare',
        'Sprint',
        'Storm',
    ], // 14
    'achre': [ // 14
        'Absorb',
        'Achire',
        'Astrave',
        'Blink',
        'Caerenesis',
        'Desperation',
        'Devour',
        'Freeze',
        'Fyerus',
        'Healing',
        'Moderate',
        'Multifarious',
        'Netherswap',
        'Polymorph',
        'Quor',
        'Reconstitute',
        'Slow'
    ], // 14 
    'caeren': [ // 14
        'Achire',
        'Astrave',
        'Blink',
        'Caerenesis',
        'Desperation',
        'Fear',
        'Fyerus',
        'Healing',
        'Ilirech',
        'Kyrnaicism',
        'Malice',
        'Menace',
        'Mend',
        'Reconstitute',
        'Sacrifice', 
        'Scream',
        'Shirk'
    ], // 14
    'kyosir': [ // 14
        'Blink',
        'Chiomic',
        'Confuse',
        'Desperation',
        'Devour',
        'Disease',
        'Dispel',
        'Healing',
        'Hook',
        'Kynisos',
        'Maiereth',
        'Malice',
        'Mystify',
        'Netherswap',
        'Protect',
        'Reconstitute',
        'Sacrifice',
        'Suture'
    ], // 14
};