const COST = {LOW: 30, MID: 50,HIGH: 70};
const DURATION = {BOTTOM: 750, STANDARD: 1500, LOW: 1000, LESSER: 3000, MODERATE: 6000, HIGH: 8000, TOP: 10000};
export const PLAYER = {
    COLLIDER: {
        DISPLACEMENT: 16,
        HEIGHT: 36,
        WIDTH: 20,
    },
    SPEED: {
        INITIAL: 1.5, // 1.75
        ACCELERATION: 0.125,
        DECELERATION: 0.05,
        CAERENIC: 0.5,
        SLOW: 1,
        SNARE: 1.5,
        SPRINT: 1.5,
        STEALTH: 0.5,
        LEAP: 300,
        BLINK: 250,
        RUSH: 300,
    },  
    SCALE: {
        SELF: 0.8,
        SHIELD: 0.6,
        WEAPON_ONE: 0.5,
        WEAPON_TWO: 0.65,
    },
    SENSOR: {
        COMBAT: 48,
        DEFAULT: 36,
        DISPLACEMENT: 12,
        EVADE: 21,
    },
    STAMINA: {
        // Physical
        ATTACK: 35,
        DODGE: 15, // 25
        PARRY: 15,
        POSTURE: 25,
        ROLL: 15, // 25
        // Magical
        // Low Cost        
        INVOKE: -COST.LOW,
        BLINK: COST.LOW,
        CONFUSE: COST.LOW,
        CONSUME: COST.LOW,
        FEAR: COST.LOW,
        HEALING: COST.LOW,
        PARALYZE: COST.LOW,
        POLYMORPH: COST.LOW,
        ROOT: COST.LOW,
        SHIMMER: COST.LOW,
        SLOW: COST.LOW,
        SPRINT: COST.LOW,
        // Moderate Cost
        ACHIRE: COST.MID,
        ARC: COST.MID,
        KYNISOS: COST.MID,
        KYRNAICISM: COST.MID,
        LEAP: COST.MID,
        PURSUIT: COST.MID,
        RUSH: COST.MID,
        SACRIFICE: COST.MID,
        SNARE: COST.MID,
        STORM: COST.MID,
        SUTURE: COST.MID,
        // High Cost
        ASTRAVE: COST.HIGH,
        DESPERATION: COST.HIGH,
        FYERUS: COST.HIGH,
        TSHAERAL: COST.HIGH,
        // Trait
        ENDURANCE: 0,
        ASTRICATION: COST.LOW,
        BERSERK: COST.LOW,
        CONVICTION: COST.LOW,
        IMPERMANENCE: COST.LOW,
        SEER: COST.LOW,
        STIMULATE: COST.LOW,
        BLIND: COST.MID,
        CAERENESIS: COST.HIGH,
        DEVOUR: COST.HIGH,
        // AoE
        CHIOMIC: COST.MID,  
        DISEASE: COST.MID,
        FREEZE: COST.MID,
        HOWL: COST.MID,
        RENEWAL: COST.MID,
        SCREAM: COST.MID,
        WRITHE: COST.MID,
        // Bubble
        ABSORB: 0,
        ENVELOP: 0,
        MALICE: COST.MID,
        MEND: COST.MID,
        PROTECT: COST.HIGH,
        RECOVER: COST.LOW,
        SHIELD: COST.HIGH,
        WARD: COST.MID,
    },
    COOLDOWNS: {
        SHORT: 6000,
        MODERATE: 10000,
        LONG: 15000,
    },
    DURATIONS: {
        ABSORB: DURATION.TOP,
        ACHIRE: DURATION.LOW,
        ASTRAVE: DURATION.STANDARD,
        ARCING: DURATION.LESSER,
        CHIOMIC: DURATION.LOW,
        CONFUSE: DURATION.LOW,
        DISEASE: DURATION.MODERATE,
        ENVELOP: DURATION.TOP,
        FEAR: DURATION.STANDARD,
        FYERUS: DURATION.MODERATE,
        FREEZE: DURATION.BOTTOM,
        HEALING: DURATION.STANDARD,
        KYNISOS: DURATION.LOW,
        KYRNAICISM: DURATION.LESSER,
        LEAP: DURATION.BOTTOM,
        MALICE: DURATION.TOP,
        MEND: DURATION.TOP,
        PROTECT: DURATION.MODERATE,
        POLYMORPH: DURATION.STANDARD,
        PARALYZE: DURATION.STANDARD,
        PURSUIT: DURATION.BOTTOM,
        RECOVER: DURATION.TOP,
        RENEWAL: DURATION.MODERATE,
        ROOTING: DURATION.LOW,
        RUSH: DURATION.BOTTOM,
        SACRIFICE: DURATION.BOTTOM,
        SCREAM: DURATION.LOW,
        SHIELD: DURATION.TOP,
        SHIMMER: DURATION.MODERATE,
        SNARE: DURATION.LOW,
        SPRINT: DURATION.MODERATE,
        STORM: DURATION.LESSER,
        STUNNED: 2500,
        TEXT: DURATION.STANDARD,
        TSHAERAL: 2000,
        WARD: DURATION.TOP,
        WRITHE: DURATION.LOW,
        // Trait
        ASTRICATION: DURATION.HIGH, // -1
        BERSERK: DURATION.HIGH,
        BLIND: DURATION.LOW,
        CAERENESIS: DURATION.LOW,
        CONVICTION: DURATION.HIGH,
        DEVOUR: 2000,
        ENDURANCE: 5000,
        IMPERMANENCE: DURATION.HIGH, // -1
        NEGATION: DURATION.HIGH, // -1
        SEER: DURATION.HIGH, // -1
        STIMULATE: DURATION.STANDARD,
        // Negative Durations
        SNARED: 5000,
        SLOWED: 5000,
    },
    RANGE: {
        SHORT: 200,
        MODERATE: 350,
        LONG: 500,
    },
};

export const STAMINA = ['attack', 'posture', 'roll', 'dodge', 'parry'];
export const staminaCheck = (stamina: number, cost: number): { success: boolean; cost: number } => {
    let success: boolean = stamina >= cost;
    return { success, cost };
};

export type faction = {
    name: string; // Name of faction type and functional key for factions[] array
    reputation: number; // 0 - 100. Higher reputation opens up dialog, quests, and trade
    named: boolean; // Unique enemies
    aggressive: boolean; // Attacks first if true
    betrayed: boolean; // Betrayed = went from aggressive = false to true, Permanent = always aggressive, no dialog
    faith: string; // Adherent || Devoted
    dialog: number; // Reputation threshold to enable dialog option
};

export const ENEMY_ENEMIES = {
    "Achreon Druid": ["Kyn'gian Shaman", "Tshaeral Shaman", "Kingsman", "Northren Wanderer"],
    "Ahn'are Apostle": ["Astral Apostle", "Licivitan Soldier", "Daethic Inquisitor", "Daethic Knight"],
    "Anashtre": ["Daethic Knight", "Soverain Blood Cloak", "Licivitan Soldier", "Daethic Inquisitor"],
    "Astral Apostle": ["Ahn'are Apostle", "Licivitan Soldier", "Daethic Inquisitor", "Daethic Knight"],
    "Cambiren Druid": ["Kyn'gian Shaman", "Tshaeral Shaman", "Kingsman", "Northren Wanderer"],
    "Chiomic Jester": ["Fang Duelist", "Fang Mercenary", "Marauder", "Shrygeian Bard"],
    "Daethic Inquisitor": ["Ilire Occultist", "Fyers Occultist", "Ma'ier Occultist", "Quor'eite Occultist", "Old Li'ivi Occultist"],
    "Daethic Knight": ["Anashtre", "Soverain Blood Cloak", "Firesworn", "Se'va Shrieker", "Quor'eite Stalker"],
    "Fang Duelist": ["Chiomic Jester", "Fang Mercenary", "Marauder", "Shrygeian Bard"],
    "Fang Mercenary": ["Chiomic Jester", "Fang Duelist", "Marauder", "Shrygeian Bard"],
    "Firesworn": ["Daethic Knight", "Fang Mercenary", "Se'va Shrieker", "Quor'eite Stalker", "Southron Wanderer"],
    "Fyers Occultist": ["Daethic Inquisitor", "Ilire Occultist", "Ma'ier Occultist", "Quor'eite Occultist", "Old Li'ivi Occultist"],
    "Ilire Occultist": ["Daethic Inquisitor", "Fyers Occultist", "Ma'ier Occultist", "Quor'eite Occultist", "Old Li'ivi Occultist"],
    "Kingsman": ["Achreon Druid", "Cambiren Druid", "Northren Wanderer", "Soverain Blood Cloak"],
    "Kyn'gian Shaman": ["Achreon Druid", "Cambiren Druid", "Southron Wanderer", "Sedyreal Guard", "Quor'eite Stalker"],
    "Licivitan Soldier": ["Old Li'ivi Occultist", "Firesworn", "Soverain Blood Cloak", "Kingsman", "Se'va Shrieker"],
    "Ma'ier Occultist": ["Daethic Inquisitor", "Fyers Occultist", "Ilire Occultist", "Quor'eite Occultist", "Old Li'ivi Occultist"],
    "Marauder": ["Fang Duelist", "Fang Mercenary", "Chiomic Jester", "Shrygeian Bard"],
    "Mavrosin Occultist": [],
    "Northren Wanderer": ["Achreon Druid", "Cambiren Druid", "Kingsman", "Soverain Blood Cloak"],
    "Nyren": ["Rahvrecur", "Se'va Shrieker", "Marauder", "Fang Mercenary"],
    "Old Li'ivi Occultist": ["Daethic Inquisitor", "Fyers Occultist", "Ilire Occultist", "Ma'ier Occultist", "Quor'eite Occultist"],
    "Quor'eite Occultist": ["Daethic Inquisitor", "Fyers Occultist", "Ilire Occultist", "Ma'ier Occultist", "Old Li'ivi Occultist"],
    "Quor'eite Stalker": ["Daethic Knight", "Firesworn", "Se'va Shrieker", "Sedyreal Guard", "Southron Wanderer"],
    "Rahvrecur": ["Nyren", "Se'va Shrieker", "Marauder", "Fang Mercenary"],
    "Se'dyrist": ["Se'va Shrieker", "Fang Mercenary", "Sedyreal Guard", "Firesworn"],
    "Sedyreal Guard": ["Se'dyrist", "Se'va Shrieker", "Firesworn", "Quor'eite Stalker", "Southron Wanderer"],
    "Se'va Shrieker": ["Se'dyrist", "Sedyreal Guard", "Firesworn", "Quor'eite Stalker", "Southron Wanderer"],
    "Shrygeian Bard": ["Chiomic Jester", "Fang Duelist", "Fang Mercenary", "Marauder"],
    "Southron Wanderer": ["Firesworn", "Quor'eite Stalker", "Sedyreal Guard", "Se'va Shrieker"],
    "Soverain Blood Cloak": ["Anashtre", "Licivitan Soldier", "Kingsman", "Northren Wanderer"],
    "Tshaeral Shaman": ["Achreon Druid", "Cambiren Druid", "Daethic Knight", "Daethic Inquisitor"],

    "Cyrian Shyne": ["King Mathyus Caderyn"],
    "Dorien Caderyn": ["Garris Ashenus"],
    "Eugenes": [""],
    "Evrio Lorian Peroumes": ["Mirio"],
    "Fierous Ashfyre": ["Synaethi Spiras"],
    "Garris Ashenus": ["Dorien Caderyn"],
    "King Mathyus Caderyn": ["Cyrian Shyne"],
    "Kreceus": ["Ahn'are Apostle", "Licivitan Soldier", "Evrio Lorian Peroumes", "Mirio"],
    "Laetrois Ath'Shaorah": ["Mavrios Ilios"],
    "Leaf": ["Kingsman", "Northren Wanderer"],
    "Lorian": ["Mavrios Ilios"],
    "Mavrios Ilios": ["Laetrois Ath'Shaorah", "Lorian"],
    "Mirio": ["Evrio Lorian Peroumes"],
    "Sera Lorian": ["Evrio Lorian Peroumes", "Dorien Caderyn"],
    "Synaethi Spiras": ["Fierous Ashfyre", "Torreous Ashfyre"],
    "Torreous Ashfyre": ["Synaethi Spiras"],
    "Tshios Ash'air": [],
    "Vincere": ["King Mathyus Caderyn", "Dorien Caderyn", "Sera Lorian", "Evrio Lorian Peroumes"]
};
export const NAMED_ENEMY = [
    "Achreus", 
    "Ah'gani",
    "Ashreu'ul", 
    "Caelan Greyne", 
    "Chios Dachreon", 
    "Cyrian Shyne", 
    "Daetheus", 
    "Dorien Caderyn", 
    "Eugenes", 
    "Evrio Lorian Peroumes", 
    "Fierous Ashfyre", 
    "Garris Ashenus", 
    "Jadei Myelle", 
    "King Mathyus Caderyn", 
    "Kreceus", 
    "Laetrois Ath'Shaorah", 
    "Leaf", 
    "Lorian", 
    "Mavros Ilios", 
    "Mirio Lorian Kyr'na", 
    "Na'shaer", 
    "Na'shaeri", 
    "Ocelot Greyne",
    "Quir'ilynis",
    "Quoreia Se'vyr",
    "Quor'estes", 
    "Rangiltan Caderyn", 
    "Relien Myelle", 
    "Sedeysus", 
    "Sera Lorian", 
    "Seria Capulo", 
    "Se'teyo Nati",
    "Synaethi Spiras", 
    "Torreous Ashfyre", 
    "Tshios Ash'air", 
    "Vincere"
];

export const namedNameCheck = (name: string) => {
    if (NAMED_ENEMY.includes(name)) {
        return true;
    } else {
        return false;
    };
};

const initFactions: faction[] = [
    {
        name: "Achreon Druid",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Ahn'are Apostle",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Anashtre",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Astral Apostle",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Cambiren Druid",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Chiomic Jester",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Daethic Inquisitor",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Devoted',
        dialog: 25,
    }, {
        name: "Daethic Knight",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Devoted',
        dialog: 25,
    }, {
        name: "Fang Duelist",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Fang Mercenary",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Firesworn",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Fyers Occultist",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Ilire Occultist",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Kingsman",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Devoted',
        dialog: 25,
    }, {
        name: "Kyn'gian Shaman",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Kyrisian Occultist",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Licivitan Soldier",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Devoted',
        dialog: 25,
    }, {
        name: "Ma'ier Occultist",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Marauder",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Northren Wanderer",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Nyren",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Old Li'ivi Occultist",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Quor'eite Occultist",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Quor'eite Stalker",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Rahvrehcur",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Se'dyrist",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Sedreal Guard",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Se'va Shrieker",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Shrygeian Bard",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Southron Wanderer",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Soverain Blood Cloak",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Tshaeral Shaman",
        reputation: 0,
        named: false,
        aggressive: true,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, { // ===== Named Enemies ===== 
        name: "Ah'gani",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Ashreu'ul",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Cyrian Shyne",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Daetheus",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Dorien Caderyn",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Devoted',
        dialog: 25,
    }, {
        name: "Eugenes",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Evrio Lorian Peroumes",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Devoted',
        dialog: 25,
    }, {
        name: "Fierous Ashfyre",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Garris Ashenus",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Devoted',
        dialog: 25,
    }, {
        name: "King Mathyus Caderyn",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Devoted',
        dialog: 25,
    }, {
        name: "Kreceus",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Laetrois Ath'Shaorah",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Devoted',
        dialog: 25,
    }, {
        name: "Leaf",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Lorian",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Devoted',
        dialog: 25,
    }, {
        name: "Mavros Ilios",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Mirio",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Devoted',
        dialog: 25,
    }, {
        name: "Quor'estes",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Relien Myelle",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Sera Lorian",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Devoted',
        dialog: 25,
    }, {
        name: "Sky",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Synaethi Spiras",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Torreous Ashfyre",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    }, {
        name: "Vincere",
        reputation: 0,
        named: true,
        aggressive: false,
        betrayed: false,
        faith: 'Adherent',
        dialog: 25,
    },
];

export class Reputation {
    public _id: string;
    public factions: faction[];
    public constructor(id: string,) {
        this._id = id;
        this.factions = initFactions;
    };
};

export const initReputation: Reputation = new Reputation('reputation');