export const audio: { key: string, value: string }[] = [
    {key: 'cymbal', value: '../assets/sounds/cymbal-long-2.wav'},
    {key: 'background', value: '../assets/sounds/background.mp3'},
    {key: 'background2', value: '../assets/sounds/background2.wav'},
    {key: 'combat', value: '../assets/sounds/combat.mp3'},
    {key: 'death', value: '../assets/sounds/death-sound.mp3'},
    {key: 'blink', value: '../assets/sounds/blink.wav'},
    {key: 'caerenic', value: '../assets/sounds/caerenic.wav'},
    {key: 'consume', value: '../assets/sounds/consume.wav'},
    {key: 'stalwart', value: '../assets/sounds/stalwart.mp3'},
    {key: 'stealth', value: '../assets/sounds/stealth.mp3'},
    {key: 'stealthing', value: '../assets/sounds/stealthing.mp3'},
    {key: 'prayer', value: '../assets/sounds/stealth.mp3'},
    {key: 'unequip', value: '../assets/sounds/unequip.wav'},
    {key: 'equip', value: '../assets/sounds/equip.wav'},
    {key: 'purchase', value: '../assets/sounds/buy_sell.wav'},
    {key: 'treasure', value: '../assets/sounds/treasure.mp3'},
    {key: 'action-button', value: '../assets/sounds/action-button.mp3'},
    {key: 'spooky', value: '../assets/sounds/daethic-magic.mp3'},
    {key: 'righteous', value: '../assets/sounds/religious.mp3'},
    {key: 'wild', value: '../assets/sounds/wild-magic.mp3'},
    {key: 'earth', value: '../assets/sounds/earth-magic.wav'},
    {key: 'fire', value: '../assets/sounds/fire-magic.mp3'},
    {key: 'frost', value: '../assets/sounds/frost-magic.mp3'},
    {key: 'lightning', value: '../assets/sounds/lightning-magic.wav'},
    {key: 'wind', value: '../assets/sounds/wind-magic.mp3'},
    {key: 'sorcery', value: '../assets/sounds/sorcery-magic.mp3'},
    {key: 'bow', value: '../assets/sounds/bow-attack.mp3'},
    {key: 'slash', value: '../assets/sounds/slash-attack.mp3'},
    {key: 'blunt', value: '../assets/sounds/blunt-attack.mp3'},
    {key: 'pierce', value: '../assets/sounds/sword-stab.mp3'},
    {key: 'dodge', value: '../assets/sounds/dodge.wav'},
    {key: 'roll', value: '../assets/sounds/roll-success.mp3'},
    {key: 'parry', value: '../assets/sounds/counter-success.mp3'},
    {key: 'weaponOrder', value: '../assets/sounds/weapon-order.mp3'},
    {key: 'phenomena', value: '../assets/sounds/phenomena.mp3'},
    {key: 'TV_Turn_On', value: '../assets/sounds/TV_Turn_On.wav'},
    {key: 'TV_Button_Press', value: '../assets/sounds/TV_Button_Press.wav'},
    {key: 'combat-round', value: '../assets/sounds/combat-round.mp3'},
    {key: 'alien-whoosh', value: '../assets/sounds/alien-whoosh.mp3'},
    {key: 'absorb', value: '../assets/sounds/absorb.wav'},
    {key: 'shield', value: '../assets/sounds/16_Atk_buff_04.wav'},
    {key: 'freeze', value: '../assets/sounds/freeze.wav'},
    {key: 'dungeon', value: '../assets/sounds/dungeon.mp3'},
    {key: 'debuff', value: '../assets/sounds/21_Debuff_01.wav'},
    {key: 'howl', value: '../assets/sounds/howl.wav'},
    {key: 'scream', value: '../assets/sounds/scream.wav'},
    {key: 'leap', value: '../assets/sounds/leap.wav'},
    {key: 'walk1', value: '../assets/sounds/walk-1.mp3'},
    {key: 'walk2', value: '../assets/sounds/walk-2.mp3'},
    {key: 'walk3', value: '../assets/sounds/walk-3.mp3'},
    {key: 'walk-crunch', value: '../assets/sounds/walk-crunch.mp3'},
    {key: 'walk-metallic', value: '../assets/sounds/walk-metallic.mp3'},
    {key: 'walk-swim', value: '../assets/sounds/walk-swim.mp3'},
    {key: 'industrial', value: '../assets/sounds/industrial.wav'},
    {key: 'isolation', value: '../assets/sounds/isolation.wav'},
];

export const image: {key: string, value:string}[] = [
    {key: 'beam', value: '../assets/gui/beam.png'},
    {key: 'cursor', value: '../assets/images/cursor.png'},
    {key: 'target', value: '../assets/gui/target_1.png'},
    {key: 'castle_outside', value: '../assets/gui/castle_outside.png'},
    {key: 'AncientForestMain', value: '../assets/gui/AncientForestMainLev-extruded.png'},
    {key: 'AncientForestDecorative', value: '../assets/gui/AncientForestDecorative.png'},
    {key: 'Camp_Graves', value: '../assets/gui/Camp_Graves.png'},
    {key: 'DeepCaveMainLev', value: '../assets/gui/MainLev.png'},
    {key: 'CampFireB', value: '../assets/gui/CampFireB.png'},
    {key: 'light1A', value: '../assets/gui/light1A.png'},

    {key: 'Castle Decoratives', value: '../assets/gui/Castle Decoratives.png'},
    {key: 'Castle Interior', value: '../assets/gui/Castle Interior.png'},
    {key: 'Castle Outside', value: '../assets/gui/Castle Outside.png'},

    {key: 'closed', value: '../assets/images/closed.png'},
    {key: 'open', value: '../assets/images/open.png'},
    {key: 'caerenic', value: '../assets/images/caerenic.png'},
    {key: 'stalwart', value: '../assets/images/stalwart.png'},
    {key: 'minimap', value: '../assets/images/minimap.png'},
    {key: 'pause', value: '../assets/images/pause.png'},
    {key: 'stealth', value: '../assets/images/stealth.png'},
    {key: 'strafe', value: '../assets/images/strafe.png'},
    {key: 'info', value: '../assets/images/info.png'},
    {key: 'settings', value: '../assets/images/settings.png'},
    {key: 'logs', value: '../assets/images/logs.png'},
    {key: 'dialog', value: '../assets/images/dialog.png'},
    {key: 'loot', value: '../assets/images/loot.png'},
    {key: 'cursor-reset', value: '../assets/images/cursor-reset.png'},
    {key: 'player-castbar', value: '../assets/gui/player-castbar.png'},
];

export const INTRO_NODES = {
    0: {
        key: 0,
        prev: undefined, // undefined
        next: 1,
        text: `This world is a menagerie of beauty and horror; full of bounty where humans gather, its jungle's reach is long and wild. Marred and mutated, this land is rife with the blood of Ancients. Beings of fantastic might and worship a thousand years past, grew civilization and genius from their worshipers. The Sundering eclipsed such flourishing; a War of the Ancients.`,
        // text: "This is a sample of the introductory text. This appears to become jittery when breaking to the second line onward. It is not starting from its left position and moving right, rather it starts from the center and is moved left as it types right. Is this still true?" 
    },
    1: {
        key: 1,
        prev: 0,
        next: 2,
        text: `Most humans died. Most who lived did so from the brilliance of General Laetrois Ath'Shaorah, prophet of Daethos, who warred against the Ancients. Humans freed from the Ancients and their homes; the Sundering's last gift to the world. For a thousand years, strange people from stranger lands clashed. Few coalesced.`,
    },
    2: {
        key: 2,
        prev: 1,
        next: 3,
        text: `And yet, the beauty of this world bloomed once more, with many curious and traversing this world, despite whispers of the old and the Ancient being seen again. Whether in their mythic forms or of an othernature altogether, perhaps not all perished in their war. Perhaps its horror has returned.`,
    },
    3: {
        key: 3,
        prev: 2,
        next: 4,
        text: `Inside of the last century, warring has ceased into an easing peace. Many fathers and sons died in its making; honored in the hearts of those still alive alive. Themselves now tranquil, or perhaps a form of placidity. For some, the Ascea is satiating; a decennial tournament full of jest and joust, where prestige and wealth is sought, and the 'va'Esai' crowned. To be 'Worthy of the Preservation of Being.'`,
    },
    4: {
        key: 4,
        prev: 3,
        next: 5,
        text: `A great, distinguishing burden befall the Ascean who claim the mantle. 
            King Mathyus Caderyn II, the Daethic, and Warden of the Eye; 
            High Lord Theogeni Spiras, Ghost Hawk of Greyrock, and Fyers Protectorate of the Firelands; 
            Evrio Lorian Peroumes, General of Licivitas, Proconsul of Licivitas, [Current va'Esai]. \n Such titles achieved post coronation.`,
    },
    5: {
        key: 5,
        prev: 4,
        next: undefined, // undefined
        text: `The Ascea may grant forms of honor, swathes of land, increased prestige, and numerous titles--yet these are base, inert. To become the Ascean, the va'Esai. To be Worthy. That is the offer. Do not listen to whispers otherwise. Do not be led astray. Do not fear the bleating of the fallen and beaten. There is nothing else.`,
    },
};